이메일 인증 및 유효성검사 수정
growth-genius/account-service pull request #9
Opened 2023-06-05 13:53 UTC by cyeji

2023-06-05 16:30 UTC, seunggulee1007 requested changes

2023-06-05 16:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/accountservice/modules/account/repository/AccountRepository.java
> +     * @return optional : 유효한 닉네임 확인 결과값
javadoc에 클론( : ) 은 빼 주세요.

2023-06-05 16:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/accountservice/modules/account/controller/AccountAuthController.java
> +     * 이메일 인증
check-email이면 이메일 존재 여부를 말하는 거 같은데 메서드 명이나 주석이랑 다른거 같네요.

2023-06-05 16:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/accountservice/modules/account/service/AccountService.java
> +        boolean validEmail = EmailValidator.getInstance().isValid(email);
변수가 아래에서 딱 한번 사용되는 것이라면 굳이 메모리에 할당할 필요 없이  if문에서 바로 사용하시는 것이 더 좋아 보입니다.

2023-06-05 16:30 UTC, seunggulee1007 commented on src/test/java/com/gg/tgather/accountservice/modules/account/service/AccountAuthServiceTest.java
>      void test_case_2() {
테스트 케이스 메서드 명을 신경써서 작성해 주세요

2023-06-05 16:30 UTC, seunggulee1007 commented on src/test/java/com/gg/tgather/accountservice/modules/account/util/AccountTestUtil.java
>      public static final String emailSample1 = "choyeji1591@gmail.com";
상수는 대문자로 표현하거나 enum으로 사용해 주세요.

2023-06-06 15:55 UTC, cyeji commented on src/test/java/com/gg/tgather/accountservice/modules/account/service/AccountAuthServiceTest.java
>      void test_case_2() {
넵 유의미한 메서드 명으로 변경했습니다.

2023-06-06 15:56 UTC, cyeji commented on src/test/java/com/gg/tgather/accountservice/modules/account/util/AccountTestUtil.java
>      public static final String emailSample1 = "choyeji1591@gmail.com";
네 변경했습니다.

2023-06-06 15:56 UTC, cyeji commented on src/main/java/com/gg/tgather/accountservice/modules/account/service/AccountService.java
> +        boolean validEmail = EmailValidator.getInstance().isValid(email);
넵 인라인 변수로 대체했습니다.

2023-06-06 15:56 UTC, cyeji commented on src/main/java/com/gg/tgather/accountservice/modules/account/controller/AccountAuthController.java
> +     * 이메일 인증
네 변경했습니다.

2023-06-06 15:56 UTC, cyeji commented on src/main/java/com/gg/tgather/accountservice/modules/account/repository/AccountRepository.java
> +     * @return optional : 유효한 닉네임 확인 결과값
네 변경했습니다.

2023-06-07 11:38 UTC, seunggulee1007 approved these changes
고생하셨습니다.

2023-06-07 11:38 UTC, merged